### ISSUE TITLE
Does not take account of contentType overrides

### ISSUE THREAD

**Issue by ghost** [bobdenotter/sitemap#7]
If I have a contentType where I have done an override in routes.yaml so that the contentType slug is not in the URL, the Sitemap does not reflect this.

Context: https://docs.bolt.cm/4.0/routing#contenttype-overrides

Example:

```
pagebinding:
  path: /{slugOrId}
  methods: [GET|POST]
  defaults:
    contentTypeSlug: page
    _controller: Bolt\Controller\Frontend\DetailController::record
```

The sitemap.xml still shows `domain.com/page/slug` instead of `domain.com/slug`

Right now I'm not familiar enough with Bolt core to devise a PR for this.
